=== narcispr/PyFretboard/shapes_xml/song_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="song">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string" />
        <xs:element name="author" type="xs:string" />
        <xs:element name="time">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="beats" type="xs:string" />
              <xs:element name="beat-type" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="section">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="chord" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="root" type="xs:string" />
                    <xs:element name="type" type="xs:string" />
                    <xs:element name="duration" type="xs:string" />
                    <xs:element name="shape" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="type" type="xs:string" />
                          <xs:element name="fingers">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="finger" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="pitch" type="xs:string" />
                                      <xs:element name="string" type="xs:string" />
                                      <xs:element name="fret" type="xs:string" />
                                      <xs:element name="function" type="xs:string" />
                                      <xs:element name="fingering" type="xs:string" />
                                      <xs:element name="barrel" type="xs:string" />
                                      <xs:element name="visual" type="xs:string" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== narcispr/PyFretboard/shapes_xml/modes2.xml
<?xml version="1.0" encoding="UTF-8"?>
<song xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="song_xml.xsd">
    <title>Modes shapes</title>
    <author>Narc√≠s Palomeras</author>
    <time>
        <beats>4</beats>
        <beat-type>4</beat-type>
    </time>
    <section id="Modes">
        <scale>
            <root>C</root>
            <type>Ionian</type>
            <shape id="5/1">
                <type>arpeggio</type>
                <fingers>
                    <finger>
                        <pitch>G</pitch>
                        <string>E</string>
                        <fret>3</fret>
                        <function>5</function>
                        <fingering>1s</fingering>
                        <barrel>False</barrel>
                        <visual>3</visual>
                    </finger>
                    <finger>
                        <pitch>A</pitch>
                        <string>E</string>
                        <fret>5</fret>
                        <function>6</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>3</visual>
                    </finger>
                    <finger>
                        <pitch>B</pitch>
                        <string>E</string>
                        <fret>7</fret>
                        <function>7</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>3</visual>
                    </finger>
                    <finger>
                        <pitch>C</pitch>
                        <string>A</string>
                        <fret>3</fret>
                        <function>1</function>
                        <fingering>1s</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>D</pitch>
                        <string>A</string>
                        <fret>5</fret>
                        <function>2</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>E</pitch>
                        <string>A</string>
                        <fret>7</fret>
                        <function>3</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>F</pitch>
                        <string>D</string>
                        <fret>3</fret>
                        <function>4</function>
                        <fingering>1s</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>G</pitch>
                        <string>D</string>
                        <fret>5</fret>
                        <function>5</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>A</pitch>
                        <string>D</string>
                        <fret>7</fret>
                        <function>6</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>B</pitch>
                        <string>G</string>
                        <fret>4</fret>
                        <function>7</function>
                        <fingering>1</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>C</pitch>
                        <string>G</string>
                        <fret>5</fret>
                        <function>1</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>D</pitch>
                        <string>G</string>
                        <fret>7</fret>
                        <function>2</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>E</pitch>
                        <string>B</string>
                        <fret>5</fret>
                        <function>3</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>F</pitch>
                        <string>B</string>
                        <fret>6</fret>
                        <function>4</function>
                        <fingering>3</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>G</pitch>
                        <string>e</string>
                        <fret>3</fret>
                        <function>5</function>
                        <fingering>1s</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>A</pitch>
                        <string>e</string>
                        <fret>5</fret>
                        <function>6</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>B</pitch>
                        <string>e</string>
                        <fret>7</fret>
                        <function>7</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                </fingers>
            </shape>

            <!--shape id="5/2">
                <type>arpeggio</type>
                <fingers>
                    <finger>
                        <pitch>F</pitch>
                        <string>E</string>
                        <fret>1</fret>
                        <function>4</function>
                        <fingering>1s</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>G</pitch>
                        <string>E</string>
                        <fret>3</fret>
                        <function>5</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>A</pitch>
                        <string>E</string>
                        <fret>5</fret>
                        <function>6</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>B</pitch>
                        <string>A</string>
                        <fret>2</fret>
                        <function>7</function>
                        <fingering>1</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>C</pitch>
                        <string>A</string>
                        <fret>3</fret>
                        <function>1</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>D</pitch>
                        <string>A</string>
                        <fret>5</fret>
                        <function>2</function>
                        <fingering>4</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>E</pitch>
                        <string>D</string>
                        <fret>2</fret>
                        <function>3</function>
                        <fingering>1</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>F</pitch>
                        <string>D</string>
                        <fret>3</fret>
                        <function>4</function>
                        <fingering>2</fingering>
                        <barrel>False</barrel>
                        <visual>0</visual>
                    </finger>
                    <finger>
                        <pitch>G</pitch>
                        <string>D</string>
                        <fret>5</fret>
